# Пример конфигурации Femida.
# Скопируйте в femida.yaml и отредактируйте под свои нужды.

tftp:
  # UDP-порт для TFTP-сервера. По умолчанию 69.
  port: 69

  # Путь к папке с файлами для раздачи.
  assets_path: storage/tftp/assets